name: Tests
on: [push, pull_request]
jobs:
  test:
    name: Python 3.10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install requirements (Python 3)
        run: pip install -r requirements-dev.txt && pip install .
      - name: Run tests
        run: pytest --cov=datapusher --cov-append --cov-report=xml --disable-warnings tests
      - name: Upload coverage report to codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
